name: Dependabot for Bun

on:
  pull_request:
    branches:
      - dependabot/*
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup bun
        uses: oven-sh/bun@v1
      - name: Install dependencies
        run: bun install

      - name: commit to dependabot branch
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "chore(deps): update dependencies"
          git push

