name: Dependabot for Bun

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["develop"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_if_dependabot:
    if: startsWith(github.head_ref, 'dependabot/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install

      - name: commit to dependabot branch
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "chore(deps): update dependencies"
          git push

